sudo: required

language: python
python: 
  - "3.6.1"
install: "pip install -r requirements.txt"

services:
  - docker

before_install:
-  docker-compose build

script:
  - docker-compose up -d
  - docker-compose run web ./manage.py makemigrations
  - docker-compose run web ./manage.py migrate
  - docker-compose run web coverage run ./manage.py test
  - docker-compose run web coverage report
  - flake8 .

deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./scripts/deploy_prod.sh
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash ./scripts/deploy_homolog.sh
      on:
        branch: devel