version: '3'

services:
  profiledb:
    image: postgres
    ports:
      - "5433:80"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8005:8000"
    depends_on:
      - profiledb
