# Generated by Django 2.1 on 2018-10-31 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
