# Generated by Django 2.1 on 2018-09-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_token', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=7)),
            ],
        ),
    ]
