# Generated by Django 2.1 on 2018-09-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carprofile',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='carprofile',
            name='car_model',
        ),
    ]
