# Generated by Django 2.1 on 2018-10-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180929_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
